/* i18n: system (chrome) strings only. Example content (chat/DM bodies,
   sample names, server/team/project names) stays Serbian and is NOT keyed. */
export const M = {
  // Topbar / channel descriptions / placeholders
  chOpsteDesc: { en: "General discussion and announcements", sr: "Opšti razgovori i najave" },
  chNajaveDesc: { en: "Organizer notifications", sr: "Obaveštenja organizatora" },
  chResursiDesc: { en: "Useful links and materials", sr: "Korisni linkovi i materijali" },
  chBountiesDesc: { en: "Sponsor challenges: apply for special prizes", sr: "Sponzorski izazovi: prijavite se za posebne nagrade" },
  chTimDigitalciDesc: { en: "Private channel of team digitalci", sr: "Privatni kanal tima digitalci" },
  chBoardDesc: { en: "Kanban board of team digitalci", sr: "Kanban tabla tima digitalci" },
  chGlasanjeDesc: { en: "Vote for projects", sr: "Glasajte za projekte" },
  chPredajaDesc: { en: "Submit the final project and video presentation", sr: "Predaja finalnog projekta i video prezentacije" },
  chRezultatiDesc: { en: "Official hackathon results", sr: "Zvanični rezultati hakathona" },
  msgPrefix: { en: "Message #", sr: "Poruka #" },
  msgPrefixDm: { en: "Message ", sr: "Poruka " },

  // Timer / labels
  startedAgoPre: { en: "started ", sr: "počelo pre " },
  startedAgoAfterH: { en: "h ", sr: "h " },
  startedAgoAfterMin: { en: "min ago", sr: "min" },
  votingOpensZero: { en: "opens in 0min", sr: "otvara se za 0min" },
  votingOpensInH: { en: "opens in ~", sr: "otvara se za ~" },
  votingOpensInMin: { en: "opens in ", sr: "otvara se za " },
  hUnit: { en: "h ", sr: "h " },
  minUnit: { en: "min", sr: "min" },
  hackEndsInH: { en: "Hackathon ends in ~", sr: "Hakathon se završava za ~" },
  hackEndsInMin: { en: "Hackathon ends in ", sr: "Hakathon se završava za " },

  // Rail tooltips / aria
  railNav: { en: "Servers and messages", sr: "Serveri i poruke" },
  backHomeAria: { en: "Back to tikimiki home", sr: "Nazad na tikimiki početnu" },
  homeTooltip: { en: "tikimiki: home", sr: "tikimiki: početna" },
  backToFeed: { en: "Back to feed", sr: "Nazad na feed" },
  navSwitchAria: { en: "Switch hackathon", sr: "Promeni hakaton" },
  navActiveHacks: { en: "Active", sr: "Aktivno" },
  navPastHacks: { en: "Past hackathons", sr: "Prošli hakatoni" },
  navYourHacks: { en: "Your hackathons", sr: "Tvoji hakatoni" },
  navNoServers: { en: "No hackathon servers yet.", sr: "Još nema hakaton servera." },
  etfServerAria: { en: "ETF HackWeek 2026: active server", sr: "ETF HackWeek 2026: aktivan server" },
  etfServerTooltip: { en: "ETF HackWeek 2026 · active", sr: "ETF HackWeek 2026 · aktivan" },
  noServerAccessTitle: { en: "No server access", sr: "Nemate pristup serveru" },
  noServerAccessSub: {
    en: "You don't have access to any hackathon server yet. Once you're accepted to a hackathon, its server appears here.",
    sr: "Još nemate pristup nijednom hakaton serveru. Čim budete primljeni na hakaton, njegov server će se pojaviti ovde.",
  },
  dmEmptyTitle: { en: "No conversations yet", sr: "Još nemaš razgovora" },
  dmEmptySub: {
    en: "Start a direct message from someone's profile, or join a hackathon to meet your team.",
    sr: "Pokreni poruku sa nečijeg profila, ili se prijavi na hakaton i upoznaj svoj tim.",
  },
  dmAria: { en: "Direct messages", sr: "Direktne poruke" },
  dmTooltip: { en: "Direct messages", sr: "Direktne poruke" },
  settings: { en: "Settings", sr: "Podešavanja" },

  // Home landing view (rail button + sections)
  homeNavLabel: { en: "Home", sr: "Početna" },
  homeNavAria: { en: "Cohor home", sr: "Cohor početna" },
  homeTab: { en: "Home", sr: "Početna" },
  homeHi: { en: "Hey, ", sr: "Zdravo, " },
  homeSub: {
    en: "Your hackathon, friends and recent chats — all in one place.",
    sr: "Tvoj hakaton, prijatelji i nedavni razgovori — sve na jednom mestu.",
  },
  homeActiveHackathon: { en: "Active hackathon", sr: "Aktivan hakaton" },
  homeNoHackathon: {
    en: "No active hackathon yet. Join one to unlock its server.",
    sr: "Još nemaš aktivan hakaton. Pridruži se nekom da otključaš njegov server.",
  },
  homeFriends: { en: "Friends", sr: "Prijatelji" },
  homeNoFriends: {
    en: "No friends yet. Add people from their profile to chat here.",
    sr: "Još nemaš prijatelje. Dodaj ljude sa njihovog profila da biste ćaskali ovde.",
  },
  homeRecent: { en: "Recent chats", sr: "Nedavni razgovori" },
  homeNoRecent: {
    en: "No conversations yet. Message a friend to get started.",
    sr: "Još nema razgovora. Pošalji poruku prijatelju da započneš.",
  },
  homeOnline: { en: "Online", sr: "Na vezi" },
  homeOffline: { en: "Offline", sr: "Van veze" },
  homeUnreadAria: { en: "Unread messages", sr: "Nepročitane poruke" },

  // Channel sidebar
  editHackathon: { en: "Edit hackathon", sr: "Uredi hakathon" },
  editHackathonAlert: { en: "Edit hackathon – edit details", sr: "Uredi hakathon – izmena detalja" },
  moderators: { en: "Moderators", sr: "Moderatori" },
  manageModsAlert: { en: "Manage moderators", sr: "Upravljanje moderatorima" },
  contentReports: { en: "Content reports", sr: "Prijave sadržaja" },
  createChannel: { en: "Create channel", sr: "Kreiraj kanal" },
  createChannelAlert: { en: "Create channel – enter name and visibility", sr: "Kreiraj kanal – unos naziva i vidljivosti" },
  secGeneral: { en: "General", sr: "Opšte" },
  secBounty: { en: "Bounty", sr: "Bounty" },
  secTeams: { en: "Teams", sr: "Timovi" },
  secKanban: { en: "Kanban", sr: "Kanban" },
  secVoting: { en: "Voting & Submission", sr: "Glasanje & Predaja" },
  rezLockedTitleHint: { en: "Available after the hackathon ends", sr: "Dostupno nakon završetka hakathona" },

  // DM sidebar
  dmSidebarTitle: { en: "Direct messages", sr: "Direktne poruke" },
  newMessage: { en: "New message", sr: "Nova poruka" },
  newMessageAlert: { en: "New message – search users", sr: "Nova poruka – pretraga korisnika" },
  group: { en: "Group", sr: "Grupa" },
  newGroupAlert: { en: "New group chat – create a group", sr: "Novo grupno ćaskanje – kreiranje grupe" },
  groupModalTitle: { en: "New group chat", sr: "Novo grupno ćaskanje" },
  groupModalEmpty: { en: "No members available.", sr: "Nema dostupnih članova." },
  groupCreate: { en: "Create", sr: "Kreiraj" },
  groupCancel: { en: "Cancel", sr: "Otkaži" },
  // Group-chat management (create modal + settings)
  grpNameLabel: { en: "Name", sr: "Naziv" },
  grpNamePh: { en: "Group name", sr: "Naziv grupe" },
  grpIconLabel: { en: "Icon", sr: "Ikonica" },
  grpMembersHeader: { en: "Members", sr: "Članovi" },
  grpCreate: { en: "Create group", sr: "Kreiraj grupu" },
  grpCancel: { en: "Cancel", sr: "Otkaži" },
  grpSettings: { en: "Group settings", sr: "Podešavanja grupe" },
  grpSettingsTitle: { en: "Group settings", sr: "Podešavanja grupe" },
  grpRename: { en: "Name & icon", sr: "Naziv i ikonica" },
  grpSave: { en: "Save changes", sr: "Sačuvaj izmene" },
  grpAddMembers: { en: "Add members", sr: "Dodaj članove" },
  grpAddBtn: { en: "Add", sr: "Dodaj" },
  grpAddAll: { en: "Add selected", sr: "Dodaj izabrane" },
  grpNoMembersToAdd: { en: "Everyone is already in this group.", sr: "Svi su već u ovoj grupi." },
  grpEditAria: { en: "Edit group", sr: "Izmeni grupu" },
  grpAvatarPreview: { en: "Group icon preview", sr: "Pregled ikonice grupe" },
  grpUploadImg: { en: "Upload image", sr: "Otpremi sliku" },
  grpUploading: { en: "Uploading…", sr: "Otprema se…" },
  grpClearIcon: { en: "Clear", sr: "Ukloni" },
  grpUploadFailed: { en: "Image upload failed", sr: "Otpremanje slike nije uspelo" },
  findOrStart: { en: "Find or start a conversation", sr: "Pronađi ili započni razgovor" },
  dmSecConversations: { en: "Conversations", sr: "Razgovori" },

  // Topbar actions
  searchInChannel: { en: "Search in channel", sr: "Pretraži u kanalu" },
  pinnedMessages: { en: "Pinned messages", sr: "Zakačene poruke" },
  toggleParticipants: { en: "Show/hide participants", sr: "Prikaži/sakrij učesnike" },

  // Predaja panel
  predajaBriefTitle: { en: "Instructions for submitting the video presentation", sr: "Uputstvo za predaju video prezentacije" },
  predajaBriefText: { en: "Each team is required to upload the final video presentation of its solution before the deadline. The video remains visible even after the hackathon ends as part of the team's portfolio.", sr: "Svaki tim je dužan da otpremi finalnu video prezentaciju svog rešenja pre isteka roka. Video ostaje vidljiv i nakon završetka hakathona kao deo portfolija tima." },
  specDuration: { en: "Duration", sr: "Trajanje" },
  specDurationVal: { en: "3 – 5 minutes", sr: "3 – 5 minuta" },
  specMaxSize: { en: "Max. size", sr: "Maks. veličina" },
  specFormats: { en: "Formats", sr: "Formati" },
  specDeadline: { en: "Submission deadline", sr: "Rok za predaju" },
  specDeadlineVal: { en: "April 12, 10:00", sr: "12. april, 10:00" },
  predajaNotePre: { en: "The video must contain: a solution demo, the technical stack and key challenges. The presentation before the jury is ", sr: "Video mora sadržati: demonstraciju rešenja, tehnički stack i ključne izazove. Prezentacija pred žirijem je " },
  predajaNoteStrong: { en: "separate", sr: "odvojena" },
  predajaNotePost: { en: " from the video submission.", sr: " od video predaje." },
  videoLabel: { en: "Video presentation", sr: "Video prezentacija" },
  videoDropTitle: { en: "The team has not uploaded a video yet", sr: "Tim još nije otpremio video" },
  videoDropSub: { en: "Click here or drag a video file (MP4, MOV, AVI · max. 500 MB)", sr: "Klikni ovde ili prevuci video fajl (MP4, MOV, AVI · maks. 500 MB)" },
  videoUpload: { en: "Upload video", sr: "Otpremi video" },
  videoReplace: { en: "Replace", sr: "Zameni" },
  videoRemove: { en: "Remove", sr: "Ukloni" },
  videoNoHtml5: { en: "Your browser does not support HTML5 video.", sr: "Vaš pregledač ne podržava HTML5 video." },
  videoErrFormat: { en: "File format is not supported. Use MP4, MOV or AVI.", sr: "Format fajla nije podržan. Koristite MP4, MOV ili AVI." },
  videoErrSize: { en: "File is too large. The maximum allowed size is 500 MB.", sr: "Fajl je prevelik. Maksimalna dozvoljena veličina je 500 MB." },
  videoMetaSuffix: { en: " MB · uploaded just now", sr: " MB · otpremljeno upravo" },
  githubLabel: { en: "GitHub repository", sr: "GitHub repozitorijum" },
  edit: { en: "Edit", sr: "Uredi" },
  save: { en: "Save", sr: "Sačuvaj" },
  githubError: { en: "Enter a valid GitHub URL (e.g. https://github.com/user/repo)", sr: "Unesite ispravan GitHub URL (npr. https://github.com/user/repo)" },
  statusTitle: { en: "Submission status", sr: "Status predaje" },
  statusVideoName: { en: "Video presentation", sr: "Video prezentacija" },
  statusUploaded: { en: "Uploaded", sr: "Otpremljeno" },
  statusNotUploaded: { en: "Not uploaded", sr: "Nije otpremljeno" },
  statusGithubName: { en: "GitHub repository", sr: "GitHub repozitorijum" },
  statusLinkAdded: { en: "Link added", sr: "Link dodat" },
  statusLinkNotAdded: { en: "Link not added", sr: "Link nije dodat" },

  // Bounties panel
  bountyOrgName: { en: "Sponsor Bounty Challenges", sr: "Sponzorski Bounty Izazovi" },
  bountyOrgDesc: { en: "Apply your team for special challenges. Every solution is automatically considered for a prize on submission.", sr: "Prijavi tim za posebne izazove. Svako rešenje se automatski razmatra za nagradu pri predaji." },
  bountyBannerPre: { en: "By applying for a bounty, your final solution will be ", sr: "Prijavom na bounty, vaše finalno rešenje biće " },
  bountyBannerStrong: { en: "automatically considered", sr: "automatski razmatrano" },
  bountyBannerPost: { en: " for that prize. A team can be applied to multiple bounties at the same time. Applying is available as long as the hackathon lasts.", sr: " za tu nagradu. Tim može biti prijavljen na više bounty-a istovremeno. Prijava je dostupna sve dok hakathon traje." },
  bountyPrizeLogitech: { en: "$500 · Gaming Gear bundle", sr: "$500 · Gaming Gear paket" },
  bountyTitleLogitech: { en: "Best user interface & UX", sr: "Najbolji korisnički interfejs & UX" },
  bountyDescLogitech: { en: "Logitech rewards the team that pays special attention to the quality of the user experience. We are looking for intuitive interactions, carefully designed navigation and accessibility. The solution does not have to use peripherals. The focus is on software UX that would feel natural for an everyday user.", sr: "Logitech nagrađuje tim koji posveti posebnu pažnju kvalitetu korisničkog iskustva. Tražimo intuitivne interakcije, pažljivo osmišljenu navigaciju i dostupnost (accessibility). Rešenje ne mora koristiti periferije. Fokus je na softverskom UX-u koji bi bio prirodan za svakodnevnog korisnika." },
  bountyPrizeAnthropic: { en: "$1000 · Claude API credits (1 yr.)", sr: "$1000 · Claude API krediti (1 god.)" },
  bountyTitleAnthropic: { en: "Most responsible use of AI", sr: "Najodgovornija primena AI-a" },
  bountyDescAnthropic: { en: "Anthropic awards the prize to the project that integrates AI into its solution in the most mature and responsible way. Especially valued are: transparency toward the user (explanation of AI decisions), privacy protection, abuse prevention and graceful degradation when AI does not work correctly. Solutions that blindly forward user input without any checks will not be considered.", sr: "Anthropic dodeljuje nagradu projektu koji na najzreliji i najodgovorniji način integriše AI u svoje rešenje. Posebno se vrednuju: transparentnost prema korisniku (objašnjenje AI odluka), zaštita privatnosti, prevencija zloupotrebe i graceful degradation kada AI ne funkcioniše ispravno. Rešenja koja slepo prosleđuju korisnički unos bez ikakvih provera neće biti razmatrana." },
  bountyPrizeJetbrains: { en: "$2000 · JetBrains All Products Pack (1 yr.)", sr: "$2000 · JetBrains All Products Pack (1 god.)" },
  bountyTitleJetbrains: { en: "Cleanest and most maintainable code", sr: "Najčistiji i najodrživiji kod" },
  bountyDescJetbrains: { en: "JetBrains values the quality of the code itself, not just the end result. Criteria include: readability and consistent project structure, test coverage (unit or integration), clear documentation and architectural decisions that scale well. Projects that use static analysis or linting tools have an advantage. The GitHub repository must be publicly available at the moment of submission.", sr: "JetBrains vrednuje kvalitet samog koda, ne samo krajnji rezultat. Kriterijumi uključuju: čitljivost i konzistentnu strukturu projekta, pokrivenost testovima (unit ili integration), jasnu dokumentaciju i arhitekturalne odluke koje se dobro skaliraju. Prednost imaju projekti koji koriste statičku analizu ili linting alate. GitHub repozitorijum mora biti javno dostupan u trenutku predaje." },
  bountyApplicantsSuffix: { en: " teams applied", sr: " timova prijavljeno" },
  bountyApplyBtn: { en: "Apply team", sr: "Prijavi tim" },
  bountyAppliedBtn: { en: "✓ Applied, Withdraw", sr: "✓ Prijavljen, Odjavi se" },
  bountyEmptyTitle: { en: "No bounties yet", sr: "Još nema bounty izazova" },
  bountyEmptySub: { en: "Sponsors have not posted any bounty challenges for this hackathon.", sr: "Sponzori još nisu objavili bounty izazove za ovaj hakaton." },

  // Bounty toasts
  bountyAppliedToastPre: { en: "Team ", sr: "Tim " },
  bountyAppliedToastMid: { en: " applied to ", sr: " prijavljen na " },
  bountyAppliedToastPost: { en: "!", sr: "!" },
  bountyUnappliedToastPre: { en: "Withdrawn from bounty ", sr: "Odjavljeni sa bounty-a " },
  bountyUnappliedToastPost: { en: ".", sr: "." },

  // Voting toasts / locked toast
  voteToastPre: { en: "Vote for ", sr: "Glas za " },
  voteToastPost: { en: " is registered!", sr: " je registrovan!" },
  channelUnlocksPre: { en: "Channel unlocks in ", sr: "Kanal se otključava za " },

  // Glasanje panel
  glasanjeOrgMeta: { en: "organizer · today 09:58", sr: "organizator · danas 09:58" },
  glasanjeSayPre: { en: "Audience voting will be open in the ", sr: "Glasanje publike biće otvoreno u " },
  glasanjeSayStrong: { en: "last 2h", sr: "poslednjih 2h" },
  glasanjeSayPost: { en: " of the hackathon. Each participant may vote for one project they liked the most.", sr: " hakathona. Svaki učesnik može da glasa za jedan projekat koji mu se najviše dopao." },
  votingLockedTitle: { en: "Voting has not started yet", sr: "Glasanje još nije počelo" },
  votingLockedSub: { en: "The organizer opens voting in the last 2h of the hackathon. You can browse the projects, but voting is not available yet.", sr: "Organizator otvara glasanje u poslednjih 2h hakathona. Možete pregledati projekte, ali glasanje još uvek nije dostupno." },
  votingOpensAtLabel: { en: "Opens at ", sr: "Otvara se u " },
  projectsLabelPre: { en: "Projects: ", sr: "Projekti: " },
  projectsLabelPost: { en: " teams", sr: " timova" },
  votesLabel: { en: "votes", sr: "glasova" },
  voteBtn: { en: "Vote", sr: "Glasaj" },
  votedBtn: { en: "✓ Voted", sr: "✓ Glasano" },
  moreProjectsCount: { en: "+23 projects", sr: "+23 projekta" },
  moreProjectsHint: { en: "· click to expand", sr: "· klikni da proširiš" },
  noProjectsYet: { en: "No projects submitted yet.", sr: "Još nema prijavljenih projekata." },

  // Rezultati panel
  rezLockedTitle: { en: "Results are not available yet", sr: "Rezultati još nisu dostupni" },
  rezLockedSub: { en: "The organizer can enter the official results only after the hackathon has ended. The channel unlocks automatically.", sr: "Organizator može uneti zvanične rezultate tek nakon što hakathon bude završen. Kanal se otključava automatski." },
  rezBriefPre: { en: "The hackathon has ended! The organizer enters the official results: ", sr: "Hakathon je završen! Organizator unosi zvanične rezultate: " },
  rezBriefStrong: { en: "team rankings, audience prize and sponsor prizes", sr: "plasman timova, nagradu publike i sponzorske nagrade" },
  rezBriefPost: { en: ". After publishing, all participants will be notified and profiles will be updated automatically.", sr: ". Nakon objave, svi učesnici će biti obavešteni i profili će biti automatski ažurirani." },
  rezFormLabel: { en: "Enter results: organizer", sr: "Unos rezultata: organizator" },
  rezGroupRanking: { en: "Team rankings", sr: "Plasman timova" },
  rezPlace1: { en: "1st place", sr: "1. mesto" },
  rezPlace2: { en: "2nd place", sr: "2. mesto" },
  rezPlace3: { en: "3rd place", sr: "3. mesto" },
  rezBadge1: { en: "★ 1st place", sr: "★ 1. mesto" },
  rezBadge2: { en: "★ 2nd place", sr: "★ 2. mesto" },
  rezBadge3: { en: "★ 3rd place", sr: "★ 3. mesto" },
  rezGroupAudience: { en: "Audience prize", sr: "Nagrada publike" },
  rezAudienceLabel: { en: "Audience prize", sr: "Nagrada publike" },
  rezAudienceRowLabel: { en: "Team with the most audience votes", sr: "Tim sa najviše glasova publike" },
  rezGroupSponsor: { en: "Sponsor prizes", sr: "Sponzorske nagrade" },
  rezSponLogitechSub: { en: "Best user interface & UX · 7 teams applied", sr: "Najbolji korisnički interfejs & UX · 7 prijavljenih timova" },
  rezWinnerLogitech: { en: "Logitech winner", sr: "Pobednik Logitech" },
  rezSponAnthropicSub: { en: "Most responsible use of AI · 12 teams applied", sr: "Najodgovornija primena AI-a · 12 prijavljenih timova" },
  rezWinnerAnthropic: { en: "Anthropic winner", sr: "Pobednik Anthropic" },
  rezSponJetbrainsSub: { en: "Cleanest and most maintainable code · 9 teams applied", sr: "Najčistiji i najodrživiji kod · 9 prijavljenih timova" },
  rezWinnerJetbrains: { en: "JetBrains winner", sr: "Pobednik JetBrains" },
  selectWinner: { en: "Select a winner", sr: "Izaberi pobednika" },
  selectTeam: { en: "Select a team", sr: "Izaberi tim" },
  rezErrAllFields: { en: "Please select all teams, the audience prize and the winners of all sponsor challenges.", sr: "Molimo izaberite sve timove, nagradu publike i pobednike svih sponzorskih izazova." },
  rezErrFallback: { en: "Please select all teams and the audience prize.", sr: "Molimo izaberite sve timove i nagradu publike." },
  rezErrDuplicate: { en: "The same team cannot be in multiple places. Check your input.", sr: "Isti tim ne može biti na više mesta. Proverite unos." },
  rezSubmit: { en: "Submit results", sr: "Podnesi rezultate" },
  rezForbidden: { en: "Only the organizer can publish results", sr: "Samo organizator može objaviti rezultate" },
  rezUpdate: { en: "Update results", sr: "Ažuriraj rezultate" },
  rezOfficial: { en: "Official results", sr: "Zvanični rezultati" },
  rezEditResults: { en: "Edit results", sr: "Izmeni rezultate" },
  rezPodium1Sub: { en: "1st place · Winner", sr: "1. mesto · Pobednik" },
  rezPodium2Sub: { en: "2nd place", sr: "2. mesto" },
  rezPodium3Sub: { en: "3rd place", sr: "3. mesto" },
  rezPodiumPubSub: { en: "Audience prize", sr: "Nagrada publike" },
  rezSponPublishedHead: { en: "Sponsor challenge winners", sr: "Pobednici sponzorskih izazova" },
  rezSponRowLogitech: { en: "Logitech · Best UX", sr: "Logitech · Najbolji UX" },
  rezSponRowAnthropic: { en: "Anthropic · Most responsible use of AI", sr: "Anthropic · Najodgovornija primena AI-a" },
  rezSponRowJetbrains: { en: "JetBrains · Cleanest code", sr: "JetBrains · Najčistiji kod" },
  rezPublishedTitle: { en: "Results are published", sr: "Rezultati su objavljeni" },
  rezTimestampDefault: { en: "Participant profiles have been updated. Everyone has been notified.", sr: "Profili učesnika su ažurirani. Svi su obavešteni." },
  rezPublishedAt: { en: "Published ", sr: "Objavljeno " },
  rezPublishedAtMid: { en: " at ", sr: " u " },
  rezPublishedAtPost: { en: " · Profiles updated", sr: " · Profili ažurirani" },
  rezNewBadge: { en: "new", sr: "novo" },

  // Kanban panel
  kanbanTitle: { en: "Kanban board: digitalci", sr: "Kanban tabla: digitalci" },
  kanbanTitlePrefix: { en: "Kanban board: ", sr: "Kanban tabla: " },
  kanbanSub: { en: "ETF HackWeek 2026 · 4 members", sr: "ETF HackWeek 2026 · 4 člana" },
  kanbanSettings: { en: "Settings", sr: "Podešavanja" },
  kanbanSettingsAlert: { en: "Board settings: add/rename/delete columns", sr: "Podešavanja table: dodaj/preimenuj/obriši kolone" },
  kanbanColTodo: { en: "To do", sr: "Za uraditi" },
  kanbanColDoing: { en: "In progress", sr: "U toku" },
  kanbanColDone: { en: "Done", sr: "Završeno" },
  kanbanAddTask: { en: "Add task", sr: "Dodaj zadatak" },
  kanbanNewCardPrompt: { en: "Task title:", sr: "Naziv zadatka:" },
  kanbanCardTitlePh: { en: "Task title", sr: "Naziv zadatka" },
  kanbanCardDescPh: { en: "Description (optional)", sr: "Opis (opciono)" },
  kanbanCreate: { en: "Add", sr: "Dodaj" },
  kanbanCancel: { en: "Cancel", sr: "Otkaži" },
  kanbanEmpty: { en: "No board yet — join a team to start one.", sr: "Još nema table — pridruži se timu da je započneš." },
  kanbanRemoveCard: { en: "Delete task", sr: "Obriši zadatak" },
  kanbanAddTodoAlert: { en: "Add task to the To do column", sr: "Dodaj zadatak u kolonu Za uraditi" },
  kanbanAddDoingAlert: { en: "Add task to the In progress column", sr: "Dodaj zadatak u kolonu U toku" },
  kanbanAddDoneAlert: { en: "Add task to the Done column", sr: "Dodaj zadatak u kolonu Završeno" },
  tagDesign: { en: "design", sr: "dizajn" },
  tagResearch: { en: "research", sr: "istraživanje" },
  tagDocs: { en: "documentation", sr: "dokumentacija" },
  tagDev: { en: "development", sr: "razvoj" },

  // Composer / typing
  typingSuffix: { en: " is typing…", sr: " kuca…" },
  addAttachment: { en: "Add attachment", sr: "Dodaj prilog" },
  writeMessage: { en: "Write a message", sr: "Napiši poruku" },
  announcementReadOnly: { en: "Only organizers can post in announcements", sr: "Samo organizatori mogu objavljivati u najavama" },
  addImage: { en: "Add image", sr: "Dodaj sliku" },
  attachFile: { en: "Attach file", sr: "Priloži fajl" },
  sendMessage: { en: "Send message", sr: "Pošalji poruku" },
  mdBold: { en: "Bold", sr: "Podebljano" },
  mdItalic: { en: "Italic", sr: "Kurziv" },
  mdStrike: { en: "Strikethrough", sr: "Precrtano" },
  mdCode: { en: "Code", sr: "Kôd" },
  mdLink: { en: "Link", sr: "Link" },
  previewMessage: { en: "Preview", sr: "Pregled" },
  editMessage: { en: "Edit", sr: "Izmeni" },
  nothingToPreview: { en: "Nothing to preview yet.", sr: "Još nema šta da se pregleda." },
  removeMedia: { en: "Remove", sr: "Ukloni" },

  // Members panel
  participants: { en: "Participants", sr: "Učesnici" },
  hackEnded: { en: "Hackathon ended", sr: "Hakathon završen" },
  hackNotStarted: { en: "Not started yet", sr: "Nije počelo" },
  remaining: { en: "Remaining", sr: "Preostalo" },
  teamsStat: { en: "Teams", sr: "Timovi" },
  prizeStat: { en: "Prize", sr: "Nagrada" },
  signUp: { en: "Sign up", sr: "Prijavi se" },
  signUpAlert: { en: "Sign up: individual hackathon registration", sr: "Prijavi se: individualna prijava na hakathon" },
  signUpTeam: { en: "Sign up with a team", sr: "Prijava sa timom" },
  signUpTeamAlert: { en: "Signing up with a team: add team members", sr: "Prijavljujem se sa timom: dodaj članove tima" },
  membersOrganizers: { en: "Organizers", sr: "Organizatori" },
  roleOrganizer: { en: "Organizer", sr: "Organizator" },
  roleCoOrganizer: { en: "Co-organizer", sr: "Co-organizator" },
  badgeOrg: { en: "org", sr: "org" },
  roleBadgeOrg: { en: "organizer", sr: "organizator" },
  statusTyping: { en: "typing…", sr: "kuca…" },
  statusAway: { en: "Away", sr: "Odsutan" },
  membersOnline: { en: "Online", sr: "Online" },
  moreOnlinePre: { en: "and ", sr: "i još " },
  moreOnlinePost: { en: " more online…", sr: " online…" },
  membersOffline: { en: "Offline", sr: "Offline" },
  offlineNotePre: { en: "", sr: "" },
  offlineNotePost: { en: " participants offline", sr: " učesnika offline" },

  // Mini profile popout (Discord-style)
  miniRolesLabel: { en: "Roles", sr: "Role" },
  miniTeamLabel: { en: "Team", sr: "Tim" },
  miniNoTeam: { en: "No team", sr: "Bez tima" },
  miniViewProfile: { en: "View full profile", sr: "Otvori pun profil" },
  dmMembersLabel: { en: "Members", sr: "Članovi" },

  // Profile right-click context menu
  pmProfile: { en: "Profile", sr: "Profil" },
  pmMessage: { en: "Message", sr: "Poruka" },
  pmAddFriend: { en: "Add friend", sr: "Dodaj prijatelja" },
  pmRemoveFriend: { en: "Remove friend", sr: "Ukloni prijatelja" },
  pmBlock: { en: "Block", sr: "Blokiraj" },
  pmUnblock: { en: "Unblock", sr: "Odblokiraj" },
  pmBlocked: { en: "User blocked", sr: "Korisnik blokiran" },
  pmUnblocked: { en: "User unblocked", sr: "Korisnik odblokiran" },
  pmFriendAdded: { en: "Friend request sent", sr: "Zahtev za prijateljstvo poslat" },

  // User strip
  online: { en: "Online", sr: "Online" },
  logout: { en: "Log out", sr: "Odjava" },
  accountMenu: { en: "Account menu", sr: "Meni naloga" },
  viewProfile: { en: "View profile", sr: "Pogledaj profil" },

  // DM stream / profile
  dmConvStartPre: { en: "This is the start of your conversation with ", sr: "Ovo je početak razgovora sa " },
  dmConvStartPost: { en: ".", sr: "." },
  today: { en: "Today", sr: "Danas" },
  dmCall: { en: "Call", sr: "Pozovi" },
  dmVideo: { en: "Video", sr: "Video" },
  dmProfileAria: { en: "Profile", sr: "Profil" },
  dmProfilePanelAria: { en: "Contact profile", sr: "Profil sagovornika" },
  dmAboutUser: { en: "About the user", sr: "O korisniku" },
  dmSharedHackathons: { en: "Shared hackathons", sr: "Zajednički hakathoni" },
  dmStatusAway: { en: "Away", sr: "Odsutan" },
  dmStatus4Members: { en: "4 members", sr: "4 člana" },
  dmGroup4Members: { en: "Group DM · 4 members", sr: "Grupni DM · 4 člana" },
  dmHackSameTeam: { en: "Same team · active", sr: "Isti tim · aktivan" },
  dmHackAllTogether: { en: "All together · active", sr: "Svi zajedno · aktivan" },

  // Chat intro (server)
  chIntroTitlePre: { en: "Welcome to #", sr: "Dobrodošli u #" },
  chIntroSubPre: { en: "This is the beginning of the ", sr: "Ovo je početak kanala " },
  chIntroSubPost: { en: " channel for ETF HackWeek 2026.", sr: " za ETF HackWeek 2026." },

  // sr-only heading
  srHeading: { en: "Cohor: messages", sr: "Cohor: poruke" },

  // DM data: full names / bios / message texts
  dmNameDigitalciTeam: { en: "digitalci (team)", sr: "digitalci (tim)" },
  dmBioNenad: { en: "Low level - ETF year 3", sr: "Low level - ETF 3. god." },
  dmBioDigitalci: { en: "Team for ETF HackWeek 2026.", sr: "Tim za ETF HackWeek 2026." },
  dmMsgKalkulator: { en: "calculator", sr: "kalkulator" },
  dmMsgDigitalac: { en: "digitalac", sr: "digitalac" },
  dmMsgRepoUp: { en: "the repo is up", sr: "repo je up" },
  dmMsgSuper: { en: "awesome", sr: "super" },

  // DM list preview rows
  dmPreviewDigitalci: { en: "Dimitrije Pešić: awesome", sr: "Dimitrije Pešić: super" },
  dmPreviewNenad: { en: "digitalac", sr: "digitalac" },

  // Static server message stream
  srvMsgGoodMorningPre: {
    en: "Good morning everyone! The hackathon starts in ",
    sr: "Dobro jutro svima! Hakathon počinje za ",
  },
  srvMsgGoodMorning2h: { en: "2 hours", sr: "2 sata" },
  srvMsgGoodMorningPost: {
    en: ". All teams should register at the reception by 10am. Good luck!",
    sr: ". Svi timovi da se prijave na recepciji do 10h. Srećno!",
  },
  srvMsgThemePre: { en: "Theme: ", sr: "Tema: " },
  srvMsgThemeVal: { en: "AI for education", sr: "AI za obrazovanje" },
  srvMsgThemePost: { en: ". Details in #resursi.", sr: ". Detalji u #resursi." },
  srvMsgFinally: {
    en: "Finally! Last year's theme was boring, this is much better 🙌",
    sr: "Konačno! Prošle godine tema bila dosadna, ovo je mnogo bolje 🙌",
  },
  srvMsgRepoQuestionPost: { en: " have you made the repo yet?", sr: " jesi već napravio repo?" },
  srvMsgRepoReply: { en: "have you made the repo yet?", sr: "jesi već napravio repo?" },
  srvMsgRepoPushed: { en: "Yes, I pushed the skeleton.", sr: "Da, push-ovao sam skeleton." },
  srvMsgAlo: { en: "hello", sr: "alo" },
  srvMsgPrivateChannel: { en: "you have a private channel", sr: "imate privatan kanal" },
  srvMsgGifAlt: { en: "GIF attached to message", sr: "GIF priložen u poruci" },
  srvMsgStartingPre: { en: " Starting in ", sr: " Počinjemo za " },
  srvMsgStarting10m: { en: "10 minutes", sr: "10 minuta" },
  srvMsgStartingPost: {
    en: "! All teams should take their seats. Kick-off in Amphitheater 1.",
    sr: "! Svi timovi da zauzmu mesta. Kick-off u Amfiteatru 1.",
  },
  srvDateSep: { en: "Saturday, April 11, 2026", sr: "Subota, 11. april 2026." },
  srvDateRecently: { en: "Recently", sr: "Nedavno" },

  // Project descriptions (voting panel)
  projEduBotDesc: {
    en: "AI assistant for personalized learning, adapts content in real time based on a student's progress.",
    sr: "AI asistent za personalizovano učenje, adaptira sadržaj u realnom vremenu na osnovu napretka studenta.",
  },
  projClassroomOSDesc: {
    en: "Smart classroom management platform with real-time tracking of student attention via CV.",
    sr: "Pametna platforma za upravljanje učionicom sa real-time praćenjem pažnje učenika putem CV.",
  },
  projQuizForgeDesc: {
    en: "Generator of tests and quizzes from teaching material using GPT-4 with automatic grading.",
    sr: "Generator testova i kvizova iz nastavnog materijala koristeći GPT-4 sa automatskim ocenjivanjem.",
  },
  projMathPathDesc: {
    en: "Interactive 3D visualizer of math concepts for high schools with voice navigation.",
    sr: "Interaktivni 3D vizualizator matematičkih koncepata za srednje škole sa glasovnom navigacijom.",
  },
  projPeerLearnDesc: {
    en: "P2P platform for peer tutoring with AI matching based on learning styles and schedules.",
    sr: "P2P platforma za vršnjačko tutorstvo sa AI matchingom na osnovu stilova učenja i rasporeda.",
  },

  // Results header time
  rezHeaderTime: { en: "April 13, 2026 at 10:00", sr: "13. april 2026. u 10:00" },

  // Kanban cards
  kanbanCardLandingTitle: { en: "Landing page design", sr: "Dizajn landing stranice" },
  kanbanCardLandingDesc: {
    en: "Mockup of the main page with a hero section",
    sr: "Mockup glavne stranice sa hero sekcijom",
  },
  kanbanCardApiTitle: { en: "Research AI APIs", sr: "Istraživanje API-ja za AI" },
  kanbanCardApiDesc: {
    en: "Compare OpenAI, Anthropic and local models",
    sr: "Uporediti OpenAI, Anthropic i lokalne modele",
  },
  kanbanCardReadmeTitle: { en: "Write README", sr: "Napisati README" },
  kanbanCardAuthTitle: { en: "Backend authentication", sr: "Backend autentifikacija" },
  kanbanCardAuthDesc: {
    en: "JWT tokens + refresh mechanism",
    sr: "JWT tokeni + refresh mehanizam",
  },
  kanbanCardSchemaTitle: { en: "Database: schema", sr: "Baza podataka: šema" },
  kanbanCardSchemaDesc: {
    en: "PostgreSQL migrations for users and teams",
    sr: "PostgreSQL migracije za korisnike i timove",
  },
  kanbanCardRepoTitle: { en: "Repository setup", sr: "Setup repozitorijuma" },
  kanbanCardRepoDesc: {
    en: "GitHub repo, .gitignore, CI/CD baseline",
    sr: "GitHub repo, .gitignore, CI/CD osnova",
  },

  // Message context menu
  ctxReact: { en: "Add reaction", sr: "Dodaj reakciju" },
  ctxEdit: { en: "Edit", sr: "Izmeni" },
  ctxReply: { en: "Reply", sr: "Odgovori" },
  ctxForward: { en: "Forward", sr: "Prosledi" },
  ctxCopy: { en: "Copy", sr: "Kopiraj" },
  ctxEdited: { en: "(edited)", sr: "(izmenjeno)" },
  ctxCopied: { en: "Message copied", sr: "Poruka kopirana" },
  ctxForwarded: { en: "Message forwarded", sr: "Poruka prosleđena" },
  ctxForwardedFrom: { en: "Forwarded from", sr: "Prosleđeno od" },
  msgReplyFallback: { en: "↩ reply", sr: "↩ odgovor" },
  ctxReplyingTo: { en: "Replying to ", sr: "Odgovor za " },
  ctxForwardTitle: { en: "Forward message", sr: "Prosledi poruku" },
  ctxForwardChannels: { en: "Channels", sr: "Kanali" },
  ctxForwardDms: { en: "Direct messages", sr: "Direktne poruke" },
  ctxEditFailed: { en: "Could not edit message", sr: "Izmena poruke nije uspela" },
  ctxEditForbidden: { en: "You can only edit your own messages", sr: "Možeš izmeniti samo svoje poruke" },
  ctxDelete: { en: "Delete", sr: "Obriši" },
  ctxDeleteConfirm: { en: "Delete message?", sr: "Obriši poruku?" },
  ctxDeleteFailed: { en: "Could not delete message", sr: "Brisanje poruke nije uspelo" },

  // Channel management (manage_channels)
  chCreateChannel: { en: "Create channel", sr: "Kreiraj kanal" },
  chNewChannelTitle: { en: "New channel", sr: "Novi kanal" },
  chNameLabel: { en: "Channel name", sr: "Naziv kanala" },
  chNamePh: { en: "e.g. resources", sr: "npr. resursi" },
  chTypeLabel: { en: "Type", sr: "Tip" },
  chTypeGeneral: { en: "General", sr: "Opšte" },
  chTypeAnnouncements: { en: "Announcements", sr: "Najave" },
  chTypePrivate: { en: "Private", sr: "Privatno" },
  chNameTaken: { en: "A channel with that name already exists", sr: "Kanal sa tim nazivom već postoji" },
  chCreate: { en: "Create", sr: "Kreiraj" },
  chCancel: { en: "Cancel", sr: "Otkaži" },
  chCreateGroup: { en: "Create group", sr: "Kreiraj grupu" },
  chNewGroupTitle: { en: "New channel group", sr: "Nova grupa kanala" },
  chGroupNameLabel: { en: "Group name", sr: "Naziv grupe" },
  chGroupNamePh: { en: "e.g. RESOURCES", sr: "npr. RESURSI" },
  chRename: { en: "Rename", sr: "Preimenuj" },
  chRenameTitle: { en: "Rename channel", sr: "Preimenuj kanal" },
  chDelete: { en: "Delete channel", sr: "Obriši kanal" },
  chDeleteConfirm: { en: "Delete this channel?", sr: "Obriši ovaj kanal?" },
  chSave: { en: "Save", sr: "Sačuvaj" },
  chSettingsTitle: { en: "Channel settings", sr: "Podešavanja kanala" },
  ctxMarkRead: { en: "Mark as read", sr: "Označi kao pročitano" },
  ctxMute: { en: "Mute channel", sr: "Utišaj kanal" },
  ctxUnmute: { en: "Unmute channel", sr: "Uključi zvuk kanala" },
  chTypeProject: { en: "Project hand-in", sr: "Predaja projekta" },
  chTypeKanban: { en: "Team kanban board", sr: "Kanban tabla tima" },
  chTypeTeam: { en: "Private team chat", sr: "Privatni chat tima" },
  chAddChannelAria: { en: "Add channel to this group", sr: "Dodaj kanal u ovu grupu" },
  chActionFailed: { en: "Action failed", sr: "Radnja nije uspela" },

  // Server settings modal
  srvSettings: { en: "Server settings", sr: "Podešavanja servera" },
  srvSettingsTitle: { en: "Server settings", sr: "Podešavanja servera" },
  srvTabOverview: { en: "Overview", sr: "Pregled" },
  srvTabRoles: { en: "Roles", sr: "Role" },
  srvTabMembers: { en: "Members", sr: "Članovi" },
  srvOvName: { en: "Server name", sr: "Naziv servera" },
  srvOvLogo: { en: "Logo", sr: "Logo" },
  srvOvBanner: { en: "Banner", sr: "Baner" },
  srvOvUpload: { en: "Upload image", sr: "Otpremi sliku" },
  srvOvUploading: { en: "Uploading…", sr: "Otprema se…" },
  srvOvClear: { en: "Clear", sr: "Ukloni" },
  srvOvSave: { en: "Save changes", sr: "Sačuvaj izmene" },
  srvOvSaved: { en: "Server updated", sr: "Server ažuriran" },
  srvUploadFailed: { en: "Image upload failed", sr: "Otpremanje slike nije uspelo" },

  // Roles tab
  srvRolesEmpty: { en: "No roles yet. Create one to grant moderation powers.", sr: "Još nema rola. Kreiraj jednu da dodeliš moderatorska ovlašćenja." },
  srvRoleMembersSuffix: { en: " members", sr: " članova" },
  srvRoleMemberOne: { en: " member", sr: " član" },
  srvRoleNoPerms: { en: "No permissions", sr: "Bez ovlašćenja" },
  srvNewRole: { en: "New role", sr: "Nova rola" },
  srvRoleNameLabel: { en: "Role name", sr: "Naziv role" },
  srvRoleNamePh: { en: "e.g. Moderator", sr: "npr. Moderator" },
  srvRolePerms: { en: "Permissions", sr: "Ovlašćenja" },
  srvRoleCreate: { en: "Create role", sr: "Kreiraj rolu" },
  srvRoleSave: { en: "Save", sr: "Sačuvaj" },
  srvRoleEdit: { en: "Edit", sr: "Izmeni" },
  srvRoleDelete: { en: "Delete", sr: "Obriši" },
  srvRoleDeleteConfirm: { en: "Delete this role? Members lose its permissions.", sr: "Obriši ovu rolu? Članovi gube njena ovlašćenja." },
  srvRoleManageMembers: { en: "Members with this role", sr: "Članovi sa ovom rolom" },
  srvRoleAddMember: { en: "Add a member…", sr: "Dodaj člana…" },
  srvRoleRemoveAria: { en: "Remove from role", sr: "Ukloni iz role" },
  srvRoleNameTaken: { en: "A role with that name already exists", sr: "Rola sa tim nazivom već postoji" },
  srvRoleCancel: { en: "Cancel", sr: "Otkaži" },

  // Members tab
  srvMembersEmpty: { en: "No members.", sr: "Nema članova." },
  srvKick: { en: "Kick", sr: "Izbaci" },
  srvKickConfirm: { en: "Kick this member?", sr: "Izbaci ovog člana?" },
  srvKicked: { en: "Member removed", sr: "Član uklonjen" },
  srvKickFailed: { en: "Could not kick member", sr: "Izbacivanje nije uspelo" },
  srvModeratorBadge: { en: "mod", sr: "mod" },
} as const;
