/**
 * tikimiki — domain types
 *
 * TypeScript types + string-literal union enums derived from the database
 * schema (docs/database_specification · v4.1). Conventions:
 *   - snake_case columns are mapped to camelCase fields.
 *   - All ids are `string` (UUID).
 *   - Timestamps are ISO-8601 `string` (the API serializes TIMESTAMPTZ as text).
 *   - Nullable columns map to `field?: T | null`.
 *
 * These are the shared shapes the whole frontend reuses. They are intentionally
 * presentation-friendly (they carry a few denormalized display fields such as
 * `avatarKind` / `initials` for display). Do NOT edit this file in page work —
 * extend locally if a page needs more.
 */

/* Enums (string-literal unions) */

export type OrgVerificationStatus = "pending" | "approved" | "rejected";

export type HackathonType = "physical" | "virtual" | "hybrid";
export type HackathonStatus = "upcoming" | "ongoing" | "finished" | "cancelled";

export type TeamRole = "leader" | "member";

export type ApplicationStatus = "pending" | "approved" | "rejected" | "waitlisted" | "withdrawn";

export type ProjectStatus = "draft" | "submitted" | "under_review" | "judged";

export type ChannelType = "general" | "announcements" | "team" | "private";

export type BadgeCategory = "participation" | "achievement" | "social" | "special";

export type CosmeticType = "username_effect" | "avatar_decoration" | "banner_effect";
export type CosmeticRarity = "common" | "rare" | "epic" | "legendary";

export type MerchOrderStatus = "pending" | "processing" | "shipped" | "delivered" | "cancelled";

export type SubscriptionPlan = "premium";
export type SubscriptionStatus = "active" | "cancelled" | "expired";

export type ReportTargetType = "user" | "post" | "comment" | "message" | "hackathon";
export type ReportStatus = "pending" | "reviewed" | "resolved" | "dismissed";

export type EntityType =
  | "user"
  | "hackathon"
  | "application"
  | "team"
  | "project"
  | "post"
  | "comment"
  | "badge"
  | "message"
  | "bounty";

export type NotificationType =
  | "application_approved"
  | "application_rejected"
  | "application_waitlisted"
  | "badge_awarded"
  | "hackathon_result_posted"
  | "hackathon_starting_soon"
  | "organization_verified"
  | "organization_rejected"
  | "new_direct_message"
  | "position_assigned"
  | "bounty_result_posted"
  | "merch_order_shipped";

/* Presentation helpers */

/** Avatar color treatment classes from app.css: `.avatar.brand|.v|.t` + org. */
export type AvatarKind = "brand" | "v" | "t" | "org";

/** Status-badge variants from app.css `.badge-*`. */
export type BadgeVariant = "live" | "upcoming" | "open" | "ended" | "closed" | "warn";

/* Core entities */

export interface User {
  userId: string;
  username: string;
  email: string;
  isEmailVerified: boolean;
  githubUsername?: string | null;
  avatarUrl?: string | null;
  bannerUrl?: string | null;
  bio?: string | null;
  lastLoginAt?: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
  /** Display-only: initials + avatar color treatment used across the UI. */
  displayName?: string;
  initials?: string;
  avatarKind?: AvatarKind;
}

export interface Member {
  userId: string;
  /** BIGINT in the DB; safe as number for display point totals. */
  points: number;
  skills?: Skill[];
}

export interface Organization {
  userId: string;
  name: string;
  websiteUrl?: string | null;
  logoUrl?: string | null;
  contactEmail?: string | null;
  verificationStatus: OrgVerificationStatus;
  reviewedBy?: string | null;
  reviewedAt?: string | null;
  rejectionReason?: string | null;
  /** Display-only initials for the org avatar (e.g. "ETF", "GZ"). */
  initials?: string;
}

export interface Skill {
  skillId: string;
  name: string;
  category?: string | null;
}

export interface Hackathon {
  hackathonId: string;
  organizationId: string;
  title: string;
  description: string;
  type: HackathonType;
  status: HackathonStatus;
  theme?: string | null;
  startsAt: string;
  endsAt: string;
  registrationDeadline: string;
  maxParticipants?: number | null;
  minTeamSize: number;
  maxTeamSize: number;
  location?: string | null;
  logoUrl?: string | null;
  bannerUrl?: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
  /* Display-only fields. */
  organizationName?: string;
  organizationInitials?: string;
  prizePool?: string;
  dateLabel?: string;
  spotsLeft?: number;
  requiredSkills?: Skill[];
}

export interface Team {
  teamId: string;
  hackathonId: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
  members?: TeamMember[];
}

export interface TeamMember {
  teamId: string;
  userId: string;
  role: TeamRole;
  joinedAt: string;
  leftAt?: string | null;
  deletedAt?: string | null;
  /** Display-only. */
  username?: string;
  initials?: string;
  avatarKind?: AvatarKind;
}

export interface Application {
  applicationId: string;
  userId: string;
  hackathonId: string;
  teamId?: string | null;
  status: ApplicationStatus;
  reviewedBy?: string | null;
  reviewedAt?: string | null;
  rejectionReason?: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface Project {
  projectId: string;
  teamId: string;
  status: ProjectStatus;
  title: string;
  description?: string | null;
  repositoryUrl?: string | null;
  videoUrl?: string | null;
  submittedAt?: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface PostAttachment {
  attachmentId: string;
  postId: string;
  url: string;
  filename?: string | null;
  position: number;
}

export interface Post {
  postId: string;
  userId: string;
  content: string;
  createdAt: string;
  editedAt?: string | null;
  deletedAt?: string | null;
  attachments?: PostAttachment[];
  /** Denormalized display fields the feed renders. */
  authorName?: string;
  authorInitials?: string;
  authorKind?: AvatarKind;
  authorVerified?: boolean;
  timeLabel?: string;
  likeCount?: number;
  commentCount?: number;
  likedByMe?: boolean;
  /** Set when the post is a promoted hackathon banner. */
  promoted?: boolean;
  hackathon?: Hackathon;
  /* Feed-filter key, e.g. "opste" | "hackathoni". */
  feed?: string;
}

export interface Comment {
  commentId: string;
  postId: string;
  userId: string;
  parentCommentId?: string | null;
  content: string;
  editedAt?: string | null;
  createdAt: string;
  deletedAt?: string | null;
}

export interface Message {
  messageId: string;
  senderId: string;
  replyToId?: string | null;
  content: string;
  sentAt: string;
  editedAt?: string | null;
  deletedAt?: string | null;
  deletedBy?: string | null;
}

export interface Channel {
  channelId: string;
  groupId: string;
  teamId?: string | null;
  type: ChannelType;
  name: string;
  position: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface Server {
  serverId: string;
  hackathonId: string;
  name: string;
  logoUrl?: string | null;
  bannerUrl?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Badge {
  badgeId: string;
  name: string;
  description: string;
  category: BadgeCategory;
  iconUrl: string;
  createdAt: string;
  updatedAt: string;
}

export interface UserBadge {
  userId: string;
  badgeId: string;
  awardedAt: string;
  badge?: Badge;
}

export interface Notification {
  notificationId: string;
  userId: string;
  type: NotificationType;
  title: string;
  body?: string | null;
  entityType?: EntityType | null;
  entityId?: string | null;
  readAt?: string | null;
  createdAt: string;
}

export interface MerchItem {
  merchId: string;
  name: string;
  description?: string | null;
  imageUrl?: string | null;
  pointCost: number;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CosmeticItem {
  cosmeticId: string;
  type: CosmeticType;
  name: string;
  description?: string | null;
  rarity: CosmeticRarity;
  /** JSONB render_data — shape varies by cosmetic type. */
  renderData: Record<string, unknown>;
  pointCost?: number | null;
  createdAt: string;
}

/* Derived / composite shapes used by feature pages */

/** A direct-message preview row (Cohor card + DM list). */
export interface DmThread {
  conversationId: string;
  name: string;
  preview: string;
  initials: string;
  avatarKind: AvatarKind;
  unread?: number;
}

/** A row on the leaderboard page. */
export interface LeaderboardEntry {
  rank: number;
  userId: string;
  username: string;
  displayName: string;
  initials: string;
  avatarKind: AvatarKind;
  points: number;
  isCurrentUser?: boolean;
}
